import { TicketDatabase } from "@/lib/ticketing";

export const demoSeed: TicketDatabase = {
  companies: [
    {
      id: "company-nexmart",
      name: "NexMart Retail",
      slug: "nexmart-retail",
      plan: "enterprise",
      industry: "Retail omnicanal",
      status: "active",
      primaryContact: "laura@nexmart.com",
      createdAt: "2026-05-10T10:00:00.000Z",
    },
    {
      id: "company-saludplus",
      name: "SaludPlus",
      slug: "saludplus",
      plan: "growth",
      industry: "Healthtech",
      status: "active",
      primaryContact: "operations@saludplus.io",
      createdAt: "2026-05-12T13:30:00.000Z",
    },
  ],
  users: [
    {
      id: "user-laura",
      companyId: "company-nexmart",
      name: "Laura Medina",
      email: "laura@nexmart.com",
      role: "client_admin",
      status: "active",
      title: "Operations Lead",
      avatar: "LM",
    },
    {
      id: "user-mateo",
      companyId: "company-nexmart",
      name: "Mateo Ruiz",
      email: "mateo@nexmart.com",
      role: "client_operator",
      status: "active",
      title: "Growth Ops",
      avatar: "MR",
    },
    {
      id: "user-ana",
      companyId: "company-saludplus",
      name: "Ana Cabrera",
      email: "ana@saludplus.io",
      role: "client_viewer",
      status: "active",
      title: "PM",
      avatar: "AC",
    },
    {
      id: "user-santi",
      companyId: null,
      name: "Santiago Ibarra",
      email: "santiago@nexops.io",
      role: "agent",
      status: "active",
      title: "Automation Specialist",
      avatar: "SI",
    },
    {
      id: "user-cami",
      companyId: null,
      name: "Camila Peralta",
      email: "camila@nexops.io",
      role: "team_lead",
      status: "active",
      title: "Delivery Lead",
      avatar: "CP",
    },
    {
      id: "user-emi",
      companyId: null,
      name: "NexOps Tech",
      email: "info@nexopstech.com",
      role: "platform_admin",
      status: "active",
      title: "Platform Admin",
      avatar: "NT",
    },
  ],
  tickets: [
    {
      id: "ticket-1",
      code: "NEX-1001",
      companyId: "company-nexmart",
      title: "Error en sincronización de leads desde formulario web",
      description:
        "Los leads del landing principal no están entrando al CRM desde hoy a las 09:30. Necesitamos revisión del webhook y retry.",
      contextUrls: [
        "https://crm.nexmart.com/webhooks/leads",
      ],
      type: "issue",
      area: "crm",
      priority: "critical",
      status: "in_progress",
      createdById: "user-mateo",
      assignedToId: "user-santi",
      createdAt: "2026-05-26T11:15:00.000Z",
      updatedAt: "2026-05-26T14:05:00.000Z",
    },
    {
      id: "ticket-2",
      code: "NEX-1002",
      companyId: "company-nexmart",
      title: "Mejora para bot de recuperación de carritos",
      description:
        "Queremos sumar personalización por categoría y stock en el agente IA que opera campañas de carritos abandonados.",
      contextUrls: [
        "https://docs.nexmart.com/carritos-abandonados",
      ],
      type: "improvement",
      area: "ai_agent",
      priority: "medium",
      status: "analysis",
      createdById: "user-laura",
      assignedToId: "user-cami",
      createdAt: "2026-05-25T16:40:00.000Z",
      updatedAt: "2026-05-26T10:00:00.000Z",
    },
    {
      id: "ticket-3",
      code: "NEX-1003",
      companyId: "company-saludplus",
      title: "Ajuste en permisos del ERP para órdenes médicas",
      description:
        "Se requiere una regla nueva para que solo supervisores aprueben determinados cambios en órdenes médicas.",
      contextUrls: [],
      type: "improvement",
      area: "erp",
      priority: "high",
      status: "waiting_for_client",
      createdById: "user-ana",
      assignedToId: "user-cami",
      createdAt: "2026-05-24T18:20:00.000Z",
      updatedAt: "2026-05-26T08:15:00.000Z",
    },
  ],
  comments: [
    {
      id: "comment-1",
      ticketId: "ticket-1",
      authorId: "user-mateo",
      visibility: "external",
      body: "Adjunté logs de la última corrida fallida y el payload del formulario.",
      createdAt: "2026-05-26T11:18:00.000Z",
    },
    {
      id: "comment-2",
      ticketId: "ticket-1",
      authorId: "user-santi",
      visibility: "internal",
      body: "Detecté timeouts en el endpoint de CRM. Estoy aplicando retry con backoff.",
      createdAt: "2026-05-26T13:05:00.000Z",
    },
    {
      id: "comment-3",
      ticketId: "ticket-1",
      authorId: "user-santi",
      visibility: "external",
      body: "Ya encontramos la causa raíz. Les confirmo cuando el flujo vuelva a quedar estable.",
      createdAt: "2026-05-26T13:40:00.000Z",
    },
  ],
  attachments: [
    {
      id: "attachment-1",
      ticketId: "ticket-1",
      name: "lead-sync-errors.log",
      sizeLabel: "118 KB",
      kind: "log",
      url: "#",
    },
    {
      id: "attachment-2",
      ticketId: "ticket-2",
      name: "brief-carritos-abandonados.pdf",
      sizeLabel: "640 KB",
      kind: "brief",
      url: "#",
    },
  ],
  history: [
    {
      id: "history-1",
      ticketId: "ticket-1",
      actorId: "user-mateo",
      type: "created",
      message: "Mateo creó el ticket con prioridad crítica.",
      createdAt: "2026-05-26T11:15:00.000Z",
    },
    {
      id: "history-2",
      ticketId: "ticket-1",
      actorId: "user-cami",
      type: "assigned",
      message: "Camila asignó el ticket a Santiago Ibarra.",
      createdAt: "2026-05-26T11:35:00.000Z",
    },
    {
      id: "history-3",
      ticketId: "ticket-1",
      actorId: "user-santi",
      type: "status_changed",
      message: "Santiago cambió el estado a En progreso.",
      createdAt: "2026-05-26T11:38:00.000Z",
    },
  ],
};
